sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t drewery/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true drewery/docker-react npm run test -- --coverage
